name: Oksana Brazell Photography
favicon: null
layout_spectrum: 0.4973437220323831
typography_spectrum: 0.9192241472192109
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.045187114272266626
  lightness: 0.8537439743522555
  saturation: 0.20713980426080525
  rhythmicContrast: 0.2718482846394181
purpose: []
