name: Oksana Brazell Photography
favicon: null
layout_spectrum: 0.18557
typography_spectrum: 0.39003
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4e2fc'
    - '#c8bbce'
    - '#a99fa8'
    - '#696170'
    - '#3d263e'
  brandStrength: 0.6875
  lightness: 0.0625
  saturation: 0.9375
  rhythmicContrast: 1
purpose: []
